JE-26997 [Enable MaxPermSize in container if RAM is > 800MB ( for Java 6, 7)] - adjustment for cartridges

diff --git a/versions/1.9/neo4j-1.9/bin/neo4j b/versions/1.9/neo4j-1.9/bin/neo4j
--- a/versions/1.9/neo4j-1.9/bin/neo4j
+++ b/versions/1.9/neo4j-1.9/bin/neo4j
@@ -29,6 +29,8 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
+. /etc/jelastic/environment
+
 FRIENDLY_NAME="Neo4j Server"
 LAUNCHD_NAME="org.neo4j.server"
 
@@ -70,9 +72,8 @@ findBaseDirAndCdThere
 source bin/utils
 parseConfig
 
-JAVA_OPTS="-server -XX:+DisableExplicitGC ${wrapper_java_additional}"
-[ -z "${wrapper_java_initmemory}" ] || JAVA_OPTS="$JAVA_OPTS -Xms${wrapper_java_initmemory}m"
-[ -z "${wrapper_java_maxmemory}" ] || JAVA_OPTS="$JAVA_OPTS -Xmx${wrapper_java_maxmemory}m"
+. ${OPENSHIFT_NEO4J_DIR}/versions/${Version}/neo4j-${Version}/bin/variablesparser.sh;
+JAVA_OPTS="-server -Djava.net.preferIPv4Stack=true -XX:+DisableExplicitGC ${wrapper_java_additional} $JAVA_OPTS"
 
 #NEO4J_SERVER_PORT=`( egrep "^org.neo4j.server.webserver.port" $NEO4J_INSTANCE/conf/neo4j-server.properties || echo 7474 ) | sed -e 's/.*=//'`
 NEO4J_SERVER_PORT=${org_neo4j_server_webserver_port:=7474}
@@ -155,8 +156,8 @@ startit() {
 
   detectrunning
   if [ $newpid ] ; then
-	     echo "Another server-process is running with [$newpid], cannot start a new one. Exiting."
-	     exit 2;
+             echo "Another server-process is running with [$newpid], cannot start a new one. Exiting."
+             exit 2;
   fi
 
   if [ $DIST_OS = "macosx" ] ; then
@@ -214,38 +215,38 @@ startit() {
 
     echo -n "process [$STARTED_PID]"
 
-	  if [ $WAIT = "true" ] ; then
-	    echo -n "... waiting for server to be ready."
-	    while kill -0 $STARTED_PID 2> /dev/null ; do
-	      ## wait for start, pick up the server listening on the port
-	      detectrunning
-	      if [ $newpid ] ; then
-	         break
-	      fi
+          if [ $WAIT = "true" ] ; then
+            echo -n "... waiting for server to be ready."
+            while kill -0 $STARTED_PID 2> /dev/null ; do
+              ## wait for start, pick up the server listening on the port
+              detectrunning
+              if [ $newpid ] ; then
+                 break
+              fi
 
-	      printf "."
-	      sleep 1
-	    done
+              printf "."
+              sleep 1
+            done
 
-	    if kill -0 $STARTED_PID 2>/dev/null ; then
-	      if [ "$newpid" != "$STARTED_PID" ] ; then
-		    rm "$PID_FILE"
-	        kill -9 $STARTED_PID
-	        echo " Failed to start within $TIMEOUT seconds."
-	        echo "$FRIENDLY_NAME failed to start, please check the logs for details."
-	        echo "If startup is blocked on a long recovery, use '$0 start-no-wait' to give the startup more time."
-	        exit 2
-	      fi
+            if kill -0 $STARTED_PID 2>/dev/null ; then
+              if [ "$newpid" != "$STARTED_PID" ] ; then
+                    rm "$PID_FILE"
+                kill -9 $STARTED_PID
+                echo " Failed to start within $TIMEOUT seconds."
+                echo "$FRIENDLY_NAME failed to start, please check the logs for details."
+                echo "If startup is blocked on a long recovery, use '$0 start-no-wait' to give the startup more time."
+                exit 2
+              fi
 
-	      echo " OK."
+              echo " OK."
         echo "Go to http://localhost:$NEO4J_SERVER_PORT/webadmin/ for administration interface."
-	      exit 0
-	    fi
+              exit 0
+            fi
 
-	    echo " Failed to start within $TIMEOUT seconds."
-	    echo "$FRIENDLY_NAME may have failed to start, please check the logs."
-	    rm "$PID_FILE"
-	    exit 1
+            echo " Failed to start within $TIMEOUT seconds."
+            echo "$FRIENDLY_NAME may have failed to start, please check the logs."
+            rm "$PID_FILE"
+            exit 1
     else
         echo "...Started the server in the background, returning..."
     fi
@@ -474,3 +475,4 @@ case "${!OPTIND}" in
 esac
 
 exit $?
+
